graph BT
    subgraph Soroban Smart Contract
    E1[User requests to borrow eBook] --> F[Check asset availability. ]
    F --> G{Is asset available?}
    G -- Yes --> H[Generate new encryption key for checkout]
    H --> I[Encrypt eBook with new key]
    I --> J[Update records: store key,  check out]
    J --> K[Store user address and return date]
    K --> L[Issue encrypted eBook to user]
    G -- No --> M[Notify user]
    M --> N{Ask Waitlist}
    N -- Yes --> O[Add to waitlist]
    O --> P[End]
    N -- No --> P[End]
    L --> P[End]
    end
    subgraph Stellar Blockchain
    A[fas:fa-book Add eBook Asset to Blockchain] --> B[Create Stellar asset for book]
    B --> C[Add custom properties<hr/><ul><li>checkedout</li><li>isbn</li><li>booktitle</li><li>author</li>]
    C --> D[Issue asset on Stellar network]
    D --> E[eBook now available]
    end

